# Generated by Django 6.0.2 on 2026-02-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_service_options_remove_service_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
