# Generated by Django 6.0.2 on 2026-02-18 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Например: 0502 800 202', max_length=20, verbose_name='Телефон')),
                ('phone_additional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный телефон')),
                ('address', models.CharField(help_text='Например: г. Бишкек, ул. Манас 60/1', max_length=300, verbose_name='Адрес')),
                ('address_map_link', models.URLField(blank=True, help_text='Ссылка на Google Maps или 2GIS', max_length=500, null=True, verbose_name='Ссылка на карту')),
                ('work_hours', models.CharField(help_text='Например: с 10:00 до 19:00', max_length=200, verbose_name='Режим работы')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('telegram', models.CharField(blank=True, help_text='Username в Telegram (например: @company)', max_length=100, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, help_text='Номер для WhatsApp', max_length=20, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('interest', models.CharField(choices=[('website', 'Разработка сайта'), ('mobile', 'Мобильное приложение'), ('crypto', 'Криптовалюта/Блокчейн'), ('design', 'Дизайн'), ('marketing', 'Маркетинг'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Что вас интересует?')),
                ('interest_other', models.CharField(blank=True, help_text='Если выбрали "Другое", уточните', max_length=200, null=True, verbose_name='Другое (укажите)')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
                'ordering': ['-created_at', '-is_processed'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Сайт для поиска и покупки авиабилетов', max_length=200, verbose_name='Название проекта')),
                ('project_type', models.CharField(choices=[('website', 'Сайт'), ('mobile', 'Мобильное приложение'), ('telegram', 'Telegram бот'), ('other', 'Другое')], default='website', max_length=100, verbose_name='Тип проекта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Превью проекта')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Мы разрабатываем лучшие цифровые продукты для вашего бизнеса', max_length=200, verbose_name='Главный заголовок')),
                ('technologies_title', models.CharField(default='Мы используем', max_length=100, verbose_name='Заголовок секции технологий')),
                ('projects_title', models.CharField(default='Наши проекты', max_length=100, verbose_name='Заголовок секции проектов')),
                ('testimonials_title', models.CharField(default='Благодарности наших клиентов', max_length=100, verbose_name='Заголовок секции отзывов')),
                ('consultation_title', models.CharField(default='Получить бесплатную консультацию', max_length=100, verbose_name='Заголовок секции консультации')),
                ('subscription_text', models.CharField(default='Мы свяжемся с вами на почте.', max_length=200, verbose_name='Текст под подпиской')),
                ('button_text', models.CharField(default='Продолжить', max_length=50, verbose_name='Текст кнопки')),
                ('all_projects_text', models.CharField(default='Все проекты', max_length=50, verbose_name='Текст кнопки "Все проекты"')),
                ('send_button_text', models.CharField(default='Отправить', max_length=50, verbose_name='Текст кнопки "Отправить"')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='Логотип компании')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/hero/', verbose_name='Изображение в hero секции')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страницы',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, help_text='SVG или PNG логотип', null=True, upload_to='technologies/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, help_text='Например: https://www.python.org/', null=True, verbose_name='Ссылка на сайт')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Например: Эмиля Тимматова', max_length=200, verbose_name='Имя клиента')),
                ('client_position', models.CharField(help_text='Например: Директор компании "Айскейс"', max_length=200, verbose_name='Должность')),
                ('client_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Компания')),
                ('client_photo', models.ImageField(blank=True, help_text='Фотография клиента (рекомендуемый размер: 100x100)', null=True, upload_to='testimonials/', verbose_name='Фото клиента')),
                ('text', models.TextField(help_text='Текст благодарности от клиента', max_length=1000, verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Оценка от 1 до 5', verbose_name='Рейтинг')),
                ('project_link', models.URLField(blank=True, help_text='Ссылка на выполненный проект', null=True, verbose_name='Ссылка на проект')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше позиция', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать на сайте?', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at', '-is_processed'], 'verbose_name': 'Контактная заявка', 'verbose_name_plural': 'Контактные заявки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Услуга/Проект', 'verbose_name_plural': 'Услуги/Проекты'},
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отображать на сайте?', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше позиция', verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, help_text='Куда ведет кнопка "Продолжить"', null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
