# Generated by Django 6.0.2 on 2026-02-18 11:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_companyinfo_consultationrequest_project_sitecontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: UX/UI дизайн', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, help_text='Например: Интерфейс / Вариации', max_length=200, null=True, verbose_name='Подзаголовок')),
                ('description', ckeditor.fields.RichTextField(help_text='Полное описание услуги с форматированием', verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, help_text='Краткое описание для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='service_details/', verbose_name='Главное изображение')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='service_details/banners/', verbose_name='Изображение для баннера')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('service', models.OneToOneField(blank=True, help_text='Связь с основной услугой', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Детальная страница услуги',
                'verbose_name_plural': 'Детальные страницы услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название кейса')),
                ('client', models.CharField(blank=True, max_length=200, null=True, verbose_name='Клиент')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание кейса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_cases/', verbose_name='Изображение')),
                ('result', models.CharField(blank=True, help_text='Например: +150% к конверсии', max_length=200, null=True, verbose_name='Результат')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='main.servicedetail', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Преимущество')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_benefits/', verbose_name='Иконка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='main.servicedetail', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', ckeditor.fields.RichTextField(help_text='Ответ на вопрос с форматированием', verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.servicedetail', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Анализ конкурентов', max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Описание особенности', null=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, help_text='Загрузите иконку', null=True, upload_to='service_features/', verbose_name='Иконка')),
                ('icon_class', models.CharField(blank=True, help_text='Или укажите CSS класс (например: bi bi-phone)', max_length=100, null=True, verbose_name='CSS класс иконки')),
                ('link', models.URLField(blank=True, help_text='Ссылка на подробнее', null=True, verbose_name='Ссылка')),
                ('link_text', models.CharField(blank=True, default='Подробнее', max_length=50, null=True, verbose_name='Текст ссылки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.servicedetail', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Особенность услуги',
                'verbose_name_plural': 'Особенности услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(help_text='1, 2, 3...', verbose_name='Номер этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание этапа')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='service_processes/', verbose_name='Иконка')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='main.servicedetail', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['step_number'],
                'unique_together': {('service_detail', 'step_number')},
            },
        ),
    ]
