# Generated by Django 6.0.2 on 2026-02-18 12:54

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_servicedetail_servicecase_servicebenefit_servicefaq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='backend', help_text=(('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')), max_length=200, verbose_name='названия вакансии')),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack')], default='backend', max_length=200, verbose_name='Категория')),
                ('level', models.CharField(choices=[('junior', 'junior'), ('middle', 'middle'), ('senior', 'senior')], default='junior', max_length=200, verbose_name='уровень квалификации')),
                ('employment_type', models.CharField(choices=[('Full-time', 'Полный рабочий день'), ('Part-time', 'Частичная занятость'), ('remote', 'Удаленная работа'), ('hybird', 'Гибридная работа'), ('internship', 'Стажировка')], default='Full-time', max_length=200, verbose_name='Тип занятости')),
                ('company_description', ckeditor.fields.RichTextField(blank=True, help_text='описание компании', null=True, verbose_name='Описание копмпании')),
                ('responsibilities', ckeditor.fields.RichTextField(help_text='обязанности', verbose_name='обязанности')),
                ('requirements', ckeditor.fields.RichTextField(help_text='Список требований к кандидату', verbose_name='Требования')),
                ('conditions', ckeditor.fields.RichTextField(help_text='Условия труда и бонусы', verbose_name='Условия работы')),
                ('additional_info', ckeditor.fields.RichTextField(blank=True, help_text='Как отправить резюме, контакты и пр.', null=True, verbose_name='Дополнительная информация')),
                ('short_description', models.TextField(blank=True, help_text='Краткое описание для карточки вакансии', max_length=300, null=True, verbose_name='Краткое описание')),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Минимальная зарплата в $', null=True, verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Максимальная зарплата в $', null=True, verbose_name='Зарплата до')),
                ('salary_text', models.CharField(blank=True, help_text='Например: "по результатам собеседования"', max_length=100, null=True, verbose_name='Текст о зарплате')),
                ('application_email', models.EmailField(blank=True, help_text='На этот email будут приходить уведомления', max_length=254, null=True, verbose_name='Email для откликов')),
                ('location', models.CharField(default='г. Бишкек', help_text='Например: г. Бишкек, ул. Манас 60/1', max_length=200, verbose_name='Локация')),
                ('is_remote', models.BooleanField(default=False, help_text='Можно работать удаленно?', verbose_name='Удаленная работа')),
                ('skills', models.CharField(blank=True, help_text='Навыки через запятую (например: Python, Django, Docker)', max_length=500, null=True, verbose_name='Ключевые навыки')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Дата, после которой вакансия не активна', null=True, verbose_name='Дата окончания')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Чем меньше число, тем выше позиция', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать вакансию на сайте?', verbose_name='Активно')),
                ('is_featured', models.BooleanField(default=False, help_text='Выделять вакансию?', verbose_name='Рекламная')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['order', '-is_featured', '-published_at'],
                'indexes': [models.Index(fields=['category', 'level', 'employment_type'], name='main_vacanc_categor_ab167b_idx'), models.Index(fields=['is_active', 'published_at'], name='main_vacanc_is_acti_84d99c_idx')],
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('social_link', models.URLField(blank=True, help_text='Ссылка на LinkedIn или другую соцсеть', max_length=500, null=True, verbose_name='Ссылка на соцсеть (LinkedIn)')),
                ('resume', models.FileField(help_text='PDF, DOC, DOCX или TXT', upload_to='vacancies/resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])], verbose_name='Резюме')),
                ('cover_letter', models.TextField(blank=True, help_text='Краткое сопроводительное письмо', null=True, verbose_name='Сопроводительное письмо')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрено'), ('interview', 'Собеседование'), ('test_task', 'Тестовое задание'), ('accepted', 'Принят'), ('rejected', 'Отказ')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки', null=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
