# Generated by Django 6.0.2 on 2026-02-18 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vacancy_vacancyapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='описание компании', null=True, verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(help_text='обязанности', verbose_name='Обязанности'),
        ),
    ]
