# Generated by Django 6.0.2 on 2026-02-18 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vacancy_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, help_text='Полное описание вакансии с форматированием', verbose_name='Описание вакансии'),
            preserve_default=False,
        ),
    ]
