"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # для загрузки переменных из .env файла

# Загрузка переменных окружения из .env файла
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-iqt29umw-l-j6q(s_5r=_46f)gk)oa5^fc2rq7rat9=snnklh6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,navis-site.onrender.com').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold admin theme
    'unfold.contrib.filters',  # Unfold filters
    'unfold.contrib.forms',  # Unfold forms
    'unfold.contrib.inlines',  # Unfold inlines
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'rest_framework',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    'whitenoise',  # added whitenoise app
    'drf_spectacular',  # Swagger/OpenAPI documentation
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL configuration (commented for testing)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'your_db_name'),
#         'USER': os.environ.get('DB_USER', 'your_db_user'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', 'your_db_password'),
#         'HOST': os.environ.get('DB_HOST', 'localhost'),
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }

# Temporary SQLite for testing
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# CKEditor settings
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'extraPlugins': 'codesnippet',
    },
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Navis Site API',
    'DESCRIPTION': 'API документация для сайта Navis - услуги, проекты, вакансии',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
    },
}

# Django Unfold settings
UNFOLD = {
    "SITE_TITLE": "Navis Admin",
    "SITE_HEADER": "Navis Administration",
    "SITE_INDEX_TITLE": "Welcome to Navis Admin Panel",
    "SITE_URL": "/",
    "HELP_TEXT": "Documentation available at: <a href='/api/docs/' target='_blank'>API Documentation</a>",
    "SHOW_DOCUMENTATION": True,
    "SHOW_SEARCH": True,
    "SHOW_HISTORY": True,
    "SIDEBAR": {
        "search": True,
        "history": True,
        "documentation": True,
    },
    "THEME": "light",
    "DASHBOARD": "unfold.contrib.dashboard",
    "NAVIGATION": [
        {
            "title": "Content Management",
            "items": [
                {
                    "title": "Services",
                    "icon": "folder",
                    "link": "admin:main_service_changelist",
                },
                {
                    "title": "Technologies", 
                    "icon": "cpu",
                    "link": "admin:main_technology_changelist",
                },
                {
                    "title": "Testimonials",
                    "icon": "message-square",
                    "link": "admin:main_testimonial_changelist",
                },
                {
                    "title": "Projects",
                    "icon": "briefcase",
                    "link": "admin:main_project_changelist",
                },
                {
                    "title": "Vacancies",
                    "icon": "users",
                    "link": "admin:main_vacancy_changelist",
                },
            ],
        },
        {
            "title": "Requests & Applications",
            "items": [
                {
                    "title": "Contact Requests",
                    "icon": "mail",
                    "link": "admin:main_contactrequest_changelist",
                },
                {
                    "title": "Consultation Requests",
                    "icon": "phone",
                    "link": "admin:main_consultationrequest_changelist",
                },
                {
                    "title": "Vacancy Applications",
                    "icon": "file-text",
                    "link": "admin:main_vacancyapplication_changelist",
                },
            ],
        },
        {
            "title": "Site Configuration",
            "items": [
                {
                    "title": "Company Info",
                    "icon": "building",
                    "link": "admin:main_companyinfo_changelist",
                },
                {
                    "title": "Site Content",
                    "icon": "layout",
                    "link": "admin:main_sitecontent_changelist",
                },
            ],
        },
        {
            "title": "API Documentation",
            "items": [
                {
                    "title": "Swagger UI",
                    "icon": "book-open",
                    "link": "/api/docs/",
                    "external": True,
                },
                {
                    "title": "ReDoc",
                    "icon": "file-text",
                    "link": "/api/redoc/",
                    "external": True,
                },
            ],
        },
    ],
}

# GET http://127.0.0.1:8000/api/services/ - список услуг
# POST http://127.0.0.1:8000/api/contact/ - создание заявки
# Admin панель: http://127.0.0.1:8000/admin/